-- =====================================================================
-- TURBOX DATABASE SCHEMA
-- Run this entire file once in your Supabase project's SQL Editor.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. TABLES
-- ---------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null check (role in ('student', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.quizzes (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  published boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  question_text text not null,
  options jsonb not null,
  correct_answer text not null,
  points integer not null default 1
);

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  score numeric not null default 0,
  total_points numeric not null default 0,
  percentage numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  file_path text,
  due_date timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  file_path text,
  grade numeric,
  feedback text,
  created_at timestamptz not null default now()
);

-- Helpful indexes
create index if not exists idx_questions_quiz_id on public.questions(quiz_id);
create index if not exists idx_quiz_attempts_student_id on public.quiz_attempts(student_id);
create index if not exists idx_quiz_attempts_quiz_id on public.quiz_attempts(quiz_id);
create index if not exists idx_submissions_student_id on public.submissions(student_id);
create index if not exists idx_submissions_assignment_id on public.submissions(assignment_id);

-- ---------------------------------------------------------------------
-- 2. SECURE ADMIN HELPER FUNCTION
-- ---------------------------------------------------------------------
-- SECURITY DEFINER + fixed search_path so it always resolves
-- public.profiles regardless of caller's search_path, and runs with the
-- privileges of the function owner so it can read profiles even though
-- RLS is enabled on that table.

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

grant execute on function public.is_admin() to authenticated;

-- ---------------------------------------------------------------------
-- 3. ROW LEVEL SECURITY
-- ---------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.quizzes enable row level security;
alter table public.questions enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.assignments enable row level security;
alter table public.submissions enable row level security;

-- --------------------- PROFILES ---------------------

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select
  using (id = auth.uid());

drop policy if exists "profiles_select_admin" on public.profiles;
create policy "profiles_select_admin"
  on public.profiles for select
  using (public.is_admin());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  using (id = auth.uid())
  with check (id = auth.uid());

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles for insert
  with check (id = auth.uid());

-- --------------------- QUIZZES ---------------------

drop policy if exists "quizzes_select_published" on public.quizzes;
create policy "quizzes_select_published"
  on public.quizzes for select
  using (published = true or public.is_admin());

drop policy if exists "quizzes_insert_admin" on public.quizzes;
create policy "quizzes_insert_admin"
  on public.quizzes for insert
  with check (public.is_admin());

drop policy if exists "quizzes_update_admin" on public.quizzes;
create policy "quizzes_update_admin"
  on public.quizzes for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "quizzes_delete_admin" on public.quizzes;
create policy "quizzes_delete_admin"
  on public.quizzes for delete
  using (public.is_admin());

-- --------------------- QUESTIONS ---------------------

drop policy if exists "questions_select_published_or_admin" on public.questions;
create policy "questions_select_published_or_admin"
  on public.questions for select
  using (
    public.is_admin()
    or exists (
      select 1 from public.quizzes q
      where q.id = questions.quiz_id
        and q.published = true
    )
  );

drop policy if exists "questions_insert_admin" on public.questions;
create policy "questions_insert_admin"
  on public.questions for insert
  with check (public.is_admin());

drop policy if exists "questions_update_admin" on public.questions;
create policy "questions_update_admin"
  on public.questions for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "questions_delete_admin" on public.questions;
create policy "questions_delete_admin"
  on public.questions for delete
  using (public.is_admin());

-- --------------------- QUIZ ATTEMPTS ---------------------

drop policy if exists "attempts_select_own_or_admin" on public.quiz_attempts;
create policy "attempts_select_own_or_admin"
  on public.quiz_attempts for select
  using (student_id = auth.uid() or public.is_admin());

drop policy if exists "attempts_insert_own" on public.quiz_attempts;
create policy "attempts_insert_own"
  on public.quiz_attempts for insert
  with check (student_id = auth.uid());

-- No update/delete policy is created for students or admins, so nobody
-- can modify or remove an attempt once submitted (including other
-- students' attempts). Admins retain read-only visibility via select.

-- --------------------- ASSIGNMENTS ---------------------

drop policy if exists "assignments_select_all" on public.assignments;
create policy "assignments_select_all"
  on public.assignments for select
  using (auth.uid() is not null);

drop policy if exists "assignments_insert_admin" on public.assignments;
create policy "assignments_insert_admin"
  on public.assignments for insert
  with check (public.is_admin());

drop policy if exists "assignments_update_admin" on public.assignments;
create policy "assignments_update_admin"
  on public.assignments for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "assignments_delete_admin" on public.assignments;
create policy "assignments_delete_admin"
  on public.assignments for delete
  using (public.is_admin());

-- --------------------- SUBMISSIONS ---------------------

drop policy if exists "submissions_select_own_or_admin" on public.submissions;
create policy "submissions_select_own_or_admin"
  on public.submissions for select
  using (student_id = auth.uid() or public.is_admin());

drop policy if exists "submissions_insert_own" on public.submissions;
create policy "submissions_insert_own"
  on public.submissions for insert
  with check (student_id = auth.uid());

drop policy if exists "submissions_update_admin" on public.submissions;
create policy "submissions_update_admin"
  on public.submissions for update
  using (public.is_admin())
  with check (public.is_admin());

-- =====================================================================
-- End of schema. See supabase/diagnostics.sql for helper queries to
-- verify your setup after running this file.
-- =====================================================================
